- name: Link .default-mix-commands
  file:
    src: "{{ dotfiles_home }}/roles/elixir/files/default-mix-commands"
    dest: "{{ dotfiles_user_home }}/.default-mix-commands"
    state: link
    force: yes

- name: Install elixir versions
  shell: mise install elixir@{{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for elixir to {{versions[0]}}
  shell: mise use -g elixir@{{versions[0]}}
  args:
    executable: /bin/bash
