export PATH=$HOME/bin:/usr/local/bin:$PATH

# mise version manager
eval "$(mise activate zsh)"

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

source $HOME/.dotfiles/roles/zsh/aliases.zsh
source $HOME/.dotfiles/roles/zsh/env.zsh
source $HOME/.dotfiles/roles/zsh/fzf.zsh

# Source non-versioned stuff
[ -f ~/.zshrc-local ] && source ~/.zshrc-local

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:/opt/homebrew/opt/postgresql@17/bin:$PATH"

# Setup direnv
eval "$(direnv hook zsh)"

# Initialize Starship prompt
eval "$(starship init zsh)"
