- name: Install golang versions
  shell: mise install golang@{{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for golang to {{versions[0]}}
  shell: mise use -g golang@{{versions[0]}}
  args:
    executable: /bin/bash
