- name: Install erlang dependencies
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - autoconf
    - build-essential
    - libncurses5-dev
    - libwxgtk3.0-gtk3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libpng-dev
    - libssh-dev
    - unixodbc-dev
    - xsltproc
    - fop
    - libxml2-utils
    - libncurses-dev
    - openjdk-11-jdk
  when: ansible_os_family == "Debian"

- name: Install erlang dependencies (macOS)
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - fop
    - libxslt
    - openssl
    - wxwidgets
  when: ansible_os_family == "Darwin"

- name: Install erlang versions
  shell: mise install erlang@{{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for erlang to {{versions[0]}}
  shell: mise use -g erlang@{{versions[0]}}
  args:
    executable: /bin/bash 