alias q="cd ..; ls"
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias up="sudo apt update && sudo apt full-upgrade && sudo apt autoremove && sudo apt autoclean"
alias bat="batcat"
alias fd="fdfind"
