- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git 
    dest: "~/.asdf"
    version: master 
    depth: 1

- name: Link .asdfrc
  file:
    src: "{{ dotfiles_home }}/roles/asdf/files/asdfrc"
    dest: "{{ dotfiles_user_home }}/.asdfrc"
    state: link
    force: yes
