- name: Set default shell to zsh
  command: chsh -s /bin/zsh {{ ansible_env.USER}}
  when: ansible_os_family == "Debian"
  become: yes

- name: Check for oh-my-zsh installation
  stat:
    path: "~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: Link .zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link
    force: yes

- name: Link .starship.toml
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/starship.toml"
    dest: "{{ dotfiles_user_home }}/.config/starship.toml"
    state: link
    force: yes

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1
