- name: Set default shell to zsh
  command: chsh -s /bin/zsh {{ ansible_env.USER}}
  become: yes

- name: Check for oh-my-zsh installation
  stat:
    path: "~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: Link .zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{ dotfiles_user_home }}/.zshrc"
    state: link
    force: yes

- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ dotfiles_user_home }}/.oh-my-zsh/custom/themes/powerlevel10k" 
    depth: 1

- name: Link .p10k.zsh
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/p10k.zsh"
    dest: "{{ dotfiles_user_home }}/.p10k.zsh"
    state: link
    force: yes
