- name: Link .default-npm-packages
  file:
    src: "{{ dotfiles_home }}/roles/node/files/default-npm-packages"
    dest: "{{ dotfiles_user_home }}/.default-npm-packages"
    state: link
    force: yes

- name: Install node versions
  shell: mise install node@{{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for node to {{versions[0]}}
  shell: mise use -g node@{{versions[0]}}
  args:
    executable: /bin/bash
