- name: Add ruby asdf plugin
  shell: source {{ dotfiles_user_home }}/.asdf/asdf.sh && asdf plugin-add ruby
  args:
    executable: /bin/bash
  register: ruby_add
  failed_when: ruby_add == 2

- name: Link .default-gems
  file:
    src: "{{ dotfiles_home }}/roles/ruby/files/default-gems"
    dest: "{{ dotfiles_user_home }}/.default-gems"
    state: link
    force: yes

- name: Install ruby versions
  shell: source {{ dotfiles_user_home }}/.asdf/asdf.sh && asdf install ruby {{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for ruby to {{versions[0]}}
  shell: source {{ dotfiles_user_home }}/.asdf/asdf.sh && asdf global ruby {{versions[0]}}
  args:
    executable: /bin/bash
