- name: Link .default-gems
  file:
    src: "{{ dotfiles_home }}/roles/ruby/files/default-gems"
    dest: "{{ dotfiles_user_home }}/.default-gems"
    state: link
    force: yes

- name: Install ruby versions
  shell: mise install ruby@{{item}}
  args:
    executable: /bin/bash
  loop: "{{versions}}"

- name: Set global version for ruby to {{versions[0]}}
  shell: mise use -g ruby@{{versions[0]}}
  args:
    executable: /bin/bash
