- name: Install MesloLGS NF font
  get_url:
    url: "{{item}}"
    dest: /usr/share/fonts/truetype
    mode: 0644
  loop: "{{meslo_lgs_nf_urls}}"
  become: yes

- name: Rebuild font cache
  command: fc-cache -f 
  become: yes
